server {
    host 0.0.0.0;
    listen 8080;
    root ./www/site1;
    max_body_size 10;

    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    location / {
        methods GET;
        index index.html;
    }

    location /upload {
        methods GET POST DELETE;
        root ./www/site1/uploads;
        upload on ./www/site1/uploads;
        directory_listing on;
    }

    location /list {
        methods GET;
        root ./www/site1/list;
        directory_listing on;
    }

    location /images {
        methods GET;
        root ./www/site1/images;
        autoindex on;
        index index.html;
    }

    location /redirect {
        redirection http://example.com;
    }

    location /cgi-bin {
        methods GET POST;
        root ./www/site1/cgi-bin;
        cgi .py /usr/bin/python3;
        cgi .sh /bin/bash;
    }
}

server {
    host 127.0.0.1;
    listen 9090;
    root ./www/site2;
    max_body_size 2000000;

    error_page 404 /errors/404.html;

    location / {
        methods GET POST;
        index home.html;
    }

    location /home {
        methods GET POST;
        index home.html;
    }

    location /upload {
        methods POST;
        upload on ./www/site2/upload;
    }

    location /list {
        methods GET;
        directory_listing on;
    }

    location /redirect {
        redirection http://example.com;
    }
}
